config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :listings do
    resources :bookings, only: [:create, :edit, :update]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  get '/my_listings', to: 'listings#my_listings', as: 'my_listings'
  patch '/bookings/:id/confirm', to: 'bookings#confirm', as: 'booking_confirm'
  patch '/bookings/:id/reject', to: 'bookings#reject', as: 'booking_reject'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :status, inclusion: { in: %w[pending confirmed rejected] }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :occupancy, presence: true

  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, :description, :address, :price_per_hour, presence: true
  validates :title, :address, uniqueness: true
  validates :price_per_hour, numericality: { only_integer: false }
  validates :description, length: { maximum: 500,
                                    too_long: "%{count} characters is the maximum allowed" }
  validates :title, length: { maximum: 60,
                              too_long: "%{count} characters is the maximum allowed" }

  include PgSearch::Model
  pg_search_scope :search_by_address,
                  against: [:address],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  # def new
  #   @listing = Listing.find(params[:listing_id])
  #   @booking = Booking.new
  # end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @listing = Listing.find(params[:listing_id])
    @booking.listing = @listing
    if @booking.save
      redirect_to bookings_path
    else
      render '/listings/show'
    end
  end

  def show
  end

  def edit
    @listing = @booking.listing
  end

  def update
    if @booking.update(booking_params)
      @booking.update(status: "pending")
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def confirm
    @booking = Booking.find(params[:id])
    @booking.update(status: "confirmed")
    redirect_to my_listings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(status: "rejected")
    redirect_to my_listings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :occupancy)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @listings = Listing.search_by_address(params[:query])
    else
      @listings = Listing.all
    end

    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        info_window: render_to_string(partial: "info_window", locals: { listing: listing })
      }
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @user = current_user
    @listing.user = @user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :edit
    end
  end

  def destroy
    @listing.destroy
    redirect_to my_listings_path
  end

  def my_listings
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :address, :price_per_hour, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @listings = Listing.all[0..2]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    @listing = @booking.listing
    if @review.save
      modify_avg_rating(@listing)
      redirect_to listing_path(@listing, anchor: "review-#{@review.id}")
    else
      render :new
    end
  end

  private

  def modify_avg_rating(listing)
    sum = 0
    listing.reviews.each { |review| sum += review.rating }
    avg = (sum / listing.reviews.length.to_f)
    listing.update(avg_rating: avg.round(2))
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h2 class="my-3">Modify your booking</h2>
      <%= simple_form_for [@listing, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :occupancy, label: "Number of guests" %>

        <span class="d-none" id="price-hour-edit-page"><%= @listing.price_per_hour %></span>
        <p id="total-price-edit-page"></p>
        <%= f.button :submit, "Send modification request", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container my-5">
  <h2>My Bookings</h2>
  <div class="row">
    <div class="col-9">
      <% current_user.bookings.each do |booking| %>
        <div class="card-booking my-3">
          <%= cl_image_tag booking.listing.photos[0].key %>
          <div class="card-booking-infos p-3">
            <h2><%= booking.listing.title %></h2>
            <p><strong>Total price: </strong>$ <%= (booking.end_date - booking.start_date) / 3600 * booking.listing.price_per_hour %> </p>
            <p><strong>Dates: </strong> <%= booking.start_date.strftime("%b %e, %l:%M %p") %> - <%= booking.end_date.strftime("%b %e, %l:%M %p") %></p>
            <p><strong>Occupancy: </strong><%= booking.occupancy %></p>
            <p><strong>Status: </strong><em><%= booking.status.capitalize %></em></p>
            <%= link_to "Cancel", booking_path(booking), method: :delete, data: { confirm: 'Are you sure you want to cancel?' } %>
            <span> | </span>
            <%= link_to "Modify", edit_listing_booking_path(booking.listing, booking) %>
            <span> | </span>
            <%= link_to "Add Review", new_booking_review_path(booking) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for [@listing, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :occupancy, label: "Number of guests" %>
    <%= f.submit "Send booking request" %>
  <% end %>
  <h5 id="total-price"></h5>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurYard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-content">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(listing) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_hour, placeholder: '$'%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit 'Create new listing', class: "btn"%>
<% end %>

app/views/listings/_info_window.html.erb
<h2><%= listing.title %></h2>
<p><%= listing.address %></p>
<p><%= "$#{listing.price_per_hour}/hour" %></p>
<p>⭐️⭐️⭐️⭐️⭐️</p>
<%= link_to "more info", listing_path(listing), class: 'btn btn-primary' %>

app/views/listings/edit.html.erb
<div class="container">
  <h1 class="my-3">Update Listing</h1>
  <%= render "form", listing: @listing %>
  <hr>

  <%= link_to listing_path(@listing), method: :delete, data: { confirm: 'Are you sure you want to delete this listing?' } do %>
  <span class="btn btn-danger">Delete Listing</span>
<% end %>
</div>

app/views/listings/index.html.erb
<!-- Header -->
<div class="main-container header-container mt-3">
  <div>
    <h2>Yards in your area</h2>
    <div>
      <%= form_tag listings_path, method: :get do %>
        <div class="input-group-append">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Enter a location" %>
          <%= submit_tag "Search", class: 'btn mx-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Content and map -->
<div class="main-container">
  <!-- Cards -->
  <div class="cards-container">
    <% @listings.each do |listing| %>
      <div class="card-listing mb-4">
        <div class="listing-img">
          <%= cl_image_tag listing.photos[0].key, crop: :thumb %>
        </div>
        <div class="listing-text">
          <h2><%= listing.title %></h2>
          <p class="address"><%= listing.address %></p>
          <p class="description"><%= listing.description %></p>
          <p><strong>
            <% if listing.avg_rating %>
              <%= "Rating: #{listing.avg_rating}" %>
            <% else %>
               <%= "New Yard!" %>
            <% end %>
            </strong></p>
          <hr>
        </div>
        <div class="listing-price">
          <h5>$<%= listing.price_per_hour %>0/hour</h5>
        </div>
        <%= link_to "more info", listing_path(listing), class: 'btn more-info-btn' %>
      </div>
    <% end %>
  </div>
  <!-- Map -->
  <div id="map"
       class= "map mt-4"
       style="width: 50%; height: 100vh; position: sticky; top: 0; box-shadow: 3px 3px 5px rgba(0,0,0,0.2); margin-bottom: 52px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/listings/my_listings.html.erb
<div class="container my-5">
  <h2>My Listings</h2>
  <br>
  <div class="row">
    <div class="col-9">
      <% current_user.listings.each do |listing| %>
        <div class="d-flex justify-content-between align-items-center">
          <h3><%= listing.title %></h3>
          <div>
            <%= link_to "Show", listing_path(listing) %>
            <span> | </span>
            <%= link_to "Edit", edit_listing_path(listing) %>
          </div>
        </div>
        <% if listing.bookings == [] %>
          <!-- <h5>No bookings yet</h5> -->
          <p><em>no reservations</em></p>
        <% else %>
          <% listing.bookings.each do |booking| %>
            <div class="card-booking ">
              <%= cl_image_tag booking.listing.photos[0].key %>
              <div class="card-booking-infos p-3">
                <p><strong>Name: </strong> <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                <p><strong>Total price:</strong> $ <%= (booking.end_date - booking.start_date) / 3600 * booking.listing.price_per_hour %> </p>
                <p><strong>Dates:</strong> <%= booking.start_date.strftime("%b %e, %l:%M %p") %> - <%= booking.end_date.strftime("%b %e, %l:%M %p") %></p>
                <p><strong>Occupancy:</strong> <%= booking.occupancy %></p>
                <p><strong>Status:</strong> <em><%= booking.status.capitalize %></em></p>
                <br>
                <% if booking.status == "pending" %>
                  <%= link_to "Approve", booking_confirm_path(booking), method: :patch, remote: true %>
                  <span> | </span>
                  <%= link_to "Deny", booking_reject_path(booking), method: :patch, remote: true %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="form-container container w-50">
  <div class="container d-flex justify-content-between mt-3">
    <h1 class="my-3">Add My Yard</h1>
  </div>
  <%= render "form", listing: @listing %>
</div>

app/views/listings/show.html.erb
<div class="container">

  <!-- Header Text -->
  <div class="show_header">
    <div class="show_header_main_text">
      <h1><%= @listing.title %></h1>
      <p><%= @listing.address %></p>
    </div>
    <div class="show_header_back">
      <%= link_to "Back to Results", listings_path, class:'btn'%>
    </div>
  </div>

  <!-- Banner with images -->
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @listing.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <div class="carousel-item active">
            <%= cl_image_tag(photo.key, alt: "Second slide", crop: :thumb, class: "d-block w-100") %>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= cl_image_tag(photo.key, alt: "Second slide", crop: :thumb, class: "d-block w-100") %>
          </div>
        <% end %>
      <% end %>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <!-- 2 column layout with details on left, booking form on right -->
  <div class="two_column_container">
    <div class="details_column">
      <div class="details_header">
        <div class="details_header_text">
          <h2>Yard details</h2>
          <p>Hosted by <%= @listing.user.first_name %></p>
          <p>$ <span id="price-hour-show-page"><%= @listing.price_per_hour %></span> / hour</p>
        </div>
        <div class="details_header_avatar">
          <%#= image_tag "https://res.cloudinary.com/dp6jmvq0j/image/upload/v1621440517/CchkFLfP_400x400_tf89lb.jpg", class: "avatar-large" %>
          <%= cl_image_tag @listing.user.photo.key, class: "avatar-large" %>
        </div>
      </div>
      <hr>

      <p><%= @listing.description %></p>
      <hr>
      <h2>Amenities</h2>
      <i class="fas fa-user-friends"></i><p>Maximum capacity: 8 people</p>
      <i class="fas fa-restroom"></i><p>Restroom available</p>
      <i class="fas fa-parking"></i><p>Parking for one vehicle</p>
      <i class="fas fa-plug"></i><p>Electrical outlets available</p>

      <hr>
      <br>
    </div>

    <div class="booking_column">
      <div class="booking_form_container">
        <div class="form-wrapper" style="width: 95%; margin: 0 auto;">
          <h2>Book this yard</h2>

          <%= simple_form_for [@listing, @booking] do |f| %>
            <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            <%= f.input :occupancy, label: "Number of guests" %>
            <p id="total-price-show-page"></p>
            <%= f.button :submit, "Send request", class: "btn" %>
          <% end %>
        </div>
      </div>

      <!-- <p>Average rating: <%= @listing.avg_rating  %></p> -->

    </div>
  </div>

</div>

<hr>
<div class="container">
  <% if @listing.reviews.blank? %>
    <h3>No reviews yet for <%= @listing.title %></h3>
  <% else %>
    <h2>Reviews (Average Rating: <%= @listing.avg_rating %>)</h2>
    <% @listing.reviews.each do |review| %>
      <div class="card my-3" id="review-<%= review.id %>">
        <div class="card-header">
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <% if review.comment.nil? %>
              <p><em>No comment left.</em></p>
            <% else %>
              <p><%= review.comment %></p>
            <% end %>
            <footer class="blockquote-footer"><%= review.booking.user.first_name %></footer>
          </blockquote>
        </div>
      </div>
     <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1585917641362-9fbb6fcfc371?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1564&q=80);">
  <div class="container">
    <h2>OurYard brings you the perfect <span id="banner-typed-text"></span>, no matter the occasion.</h2>
    <p>Reserve yours now.</p>
    <%= link_to "Explore", listings_path, class: "btn px-5 py-2" %>
  </div>
</div>
<!-- <div class="text-center">
  <%= link_to 'Create a new listing', new_listing_path, class: 'btn btn-success btn-listing px-3 py-2 m-3' %>
</div> -->

<!-- Mock up header for lower cards -->
<div class="d-flex justify-content-between align-items-end p-0 mt-1 mx-5">
  <h3>Our Top Picks</h3>
  <%= link_to 'Add Your Yard', new_listing_path, class: 'btn px-3 py-2 m-3' %>
</div>
<!-- Cards -->
<!-- <h3 class="top mx-5">Our top 3 picks for you!</h3> -->

<div class="home-card-container">
  <% @listings.each do |listing| %>
    <%= link_to listing_path(listing) do %>
      <div class="home-card rounded p-3">
        <%= cl_image_tag(listing.photos[0].key, alt: "", crop: :thumb) %>
        <div class="home-card-infos p-2">
          <div>
            <h3><%= listing.title %></h3>
            <p class="description"><%= listing.description %></p>
          </div>
          <div class="container d-flex justify-content-between p-0 mt-1">
            <p class="rating">
              <% if listing.avg_rating %>
                <%= "Rating: #{listing.avg_rating}" %>
              <% else %>
                 <%= "New Yard!" %>
              <% end %>
            </p>
            <h5 class="home-card-pricing"><%= "$#{listing.price_per_hour}/hour" %></h5>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h2 class="my-3">Rate your stay at <%= @booking.listing.title %></h2>
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :rating, label:"Rating (1-5)" %>
        <%= f.input :comment %>
        <%= f.submit 'Save review', class: "btn btn-success"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "OurYardLogoSymbol.png" %>
  <% end %>
  <%= image_tag "NameOurYard.png", class: "logo-name"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dp6jmvq0j/image/upload/v1621536617/Screen_Shot_2021-05-20_at_2.50.04_PM_golmvm.png", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My Listings", my_listings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>